apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  template:
    spec:
      containers:
      - name: mysql-init
        image: mysql:8
        command: ["sh", "-c"]
        args:
          - |
            echo "Waiting for MySQL to be ready..." &&
            until mysql -h mysql-service -u lugxuser -plugxpass -e "SELECT 1"; do
              sleep 5;
            done &&
            echo "Running schema initialization..." &&
            mysql -h mysql-service -u lugxuser -plugxpass lugx < /init/init.sql
        volumeMounts:
        - name: init-script
          mountPath: /init
      restartPolicy: OnFailure
      volumes:
      - name: init-script
        configMap:
          name: mysql-init-script
